configapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),

]

tasks/urls.py
from django.urls import path
from .views import (
    index,
    updateTodo,
    deleteTodo,
)
app_name = 'tasks'
urlpatterns = [
    path('', index, name='todo-list' ),
    path('<pk>/update/', updateTodo, name='update-todo' ),
    path('<pk>/delete/', deleteTodo, name='delete-todo' ),

]

tasks/models.py
from django.db import models
import uuid

# Create your models here.
class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    description = models.TextField()
    complete = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.title)

tasks/forms.py
from django import forms
from django.forms import ModelForm, fields, widgets
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'complete']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Title'}),
            'description': forms.TextInput(attrs={'class': 'textarea', 'placeholder': 'Describe your task here', 'cols':30, 'rows':3}),
        }

tasks/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Task
from .forms import TaskForm

# Create your views here.


def index(request):
    tasks = Task.objects.all()
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:todo-list')
    context = {'tasks': tasks, 'form': form}
    return render(request, 'tasks/todo-list.html', context)


def updateTodo(request, pk):
    obj = get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=obj)
    if request.method == 'POST':
        form = TaskForm(request.POST,instance=obj)
        if form.is_valid():
            form.save()
            return redirect('tasks:todo-list')
    context = {'obj': obj, 'form': form}
    return render(request, 'tasks/update.html', context)


def deleteTodo(request, pk):
    obj = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        obj.delete()
        return redirect('tasks:todo-list')
    context = {'obj': obj}
    return render(request, 'tasks/delete.html', context)

tasks/templates/tasks/delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Delete{% endblock title %}
{% block content %}
<h2>Delete Task</h2>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    <div class="field is-grouped">
        <div class="control">
            <input type="submit" class="button is-primary is-light" name="submit">
        </div>
        <div class="control">
            <a href="{% url 'tasks:todo-list' %}" class="button is-link is-light">Cancel</a>
        </div>
    </div>
</form>
{% endblock content %}

tasks/templates/tasks/todo-list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<h1><b>ToDo App</b></h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <div class="field">
        <div class="control">
            {{form.title}}
        </div>
    </div>
    <div class="field">
        <div class="control">
            {{form.description}}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <input type="submit" class="button is-primary is-light" name="submit">
        </div>
    </div>
</form>
<br>
{% for task in tasks %}
<div class="box">
    <article class="media">
        <div class="media-left">

        </div>
        <div class="media-content">
            {% if task.complete %}
            <strike>
                <p>
                    <b>{{task.title}}</b>
                </p>
                <span>{{task.description}}</span>
            </strike>
            {% else %}
            <b>
                <p>{{task.title}}</p>
            </b>
            <span>{{task.description}}</span>
            {% endif %}
        </div>
        <span class="icon is-pulled-right">
            <a href="{% url 'tasks:update-todo' task.id %}">
                <i class="fas fa-pen"></i>
            </a>
        </span>
        <span class="icon is-pulled-right">
            <a href="{% url 'tasks:delete-todo' task.id %}">
                <i class="fas fa-trash"></i>
            </a>
        </span>
    </article>

</div>
{% endfor %}
{% endblock content %}

tasks/templates/tasks/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update{% endblock title %}
{% block content %}
<h2>Update Task</h2>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <div class="field">
        <div class="control">
            {{form.title}}
        </div>
    </div>
    <div class="field">
        <div class="control">
            {{form.description}}
        </div>
    </div>
    <div class="field">
        <div class="control">
            <label class="checkbox">
                <input type="checkbox" name="complete"  {% if obj.complete %}checked{% endif %}>
                Mark as Complete
            </label>
        </div>
    </div>
    <div class="field is-grouped">
        <div class="control">
            <input type="submit" class="button is-primary is-light" name="submit">
        </div>
        <div class="control">
            <a href="{% url 'tasks:todo-list' %}" class="button is-link is-light">Cancel</a>
        </div>
    </div>
</form>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ToDoApp|{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/c91bc33520.js" crossorigin="anonymous"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
     {% block content %}
     {% endblock content %}
    </div>
  </section>
  </body>
</html>